### ISSUE TITLE
Couldn't open "View Logistics Wizard in Action"

### ISSUE THREAD

**Issue by cenyuzhang** [IBM-Bluemix/logistics-wizard-kubernetes#1]
After successfully deployed everything (Istio, toolchain etc.), the Logistics Wizard is up running. But when I clicked the button "View Logistics Wizard in Action". Nothing happened. In the browser developer console, it shows the following error - {"message": "ERP threw error creating new Demo", "code": 500, "user_details": "ERP threw error creating new Demo"}

Screenshot: 
<img width="1404" alt="error msg" src="https://user-images.githubusercontent.com/17069714/28756963-dc6882aa-753e-11e7-9419-c6171ea7b5b2.png">

**Comment by l2fprod** [comment]
@cenyuzhang

A few things to check:

1/ Go into the pipeline and look at the build file logs for any issue

2/ Try connecting directly to the ERP service at: http://your-cluster-ip:your-istio-ingress-port/lw/erp/explorer/

It should show the Swagger explorer for the ERP API.

3/ Try
```
curl -X POST http://your-cluster-ip:your-istio-ingress-port/lw/erp/api/v1/Demos
```
to simulate what happens when you click "View LW in action"

**Comment by cenyuzhang** [comment]
@l2fprod thanks for getting back!

The pipeline was built successfully, also 2) & 3) returned successfully.

I found in the Logistics Wizard UI, when the button "View Logistics Wizard In Action" was clicked, a different URL was called - http://your-cluster-ip:your-istio-ingress-port/lw/controller/api/v1/demos. instead of the .../lw/erp/api/v1/Demos. Maybe this is why the demo couldn't be launched?

**Comment by l2fprod** [comment]
no, the ui should call the controller this is correct. I was asking you to call the erp service directly to make sure this service works. Now we can try the controller itself:
```
curl -X POST http://your-cluster-ip:your-istio-ingress-port/lw/controller/api/v1/demos
```

**Comment by cenyuzhang** [comment]
@l2fprod Thanks. If I try the controller itself directly, I got the error message:

{"message": "ERP threw error creating new Demo", "code": 500, "user_details": "ERP threw error creating new Demo"}

FYI. When trying the ERP, the result was successful. Here is a sample of what I got back from the curl command:

{"createdAt":"2017-08-04T21:56:46.650Z","guid":"2976","id":2,"users":[{"username":"Supply Chain Manager (rGxdc8UE8p)","email":"chris.rGxdc8UE8p@acme.com","created":null,"id":2,"demoId":2,"roles":[{"id":1,"name":"supplychainmanager","description":null,"created":"2017-07-30T20:12:10.572Z","modified":"2017-07-30T20:12:10.572Z"}]}]}

**Comment by l2fprod** [comment]
so something is wrong in the communication between Controller and ERP services.

1/ which version of Istio did your install in your cluster? I tested 0.1.6
2/ can you check the controller logs in the kube console? anything there when you call the /v1/demos endpoint with curl?

**Comment by cenyuzhang** [comment]
I am using 0.1.6 too. From the controller logs in the kube console, it shows the same error. See below:

 2017-08-05T14:41:44.897317984Z ERROR in __init__ [/app/server/web/__init__.py:71]:
2017-08-05T14:41:44.897331001Z (APIException(...), 'ERP threw error creating new Demo') {'internal_details': "('Connection aborted.', error(104, 'Connection reset by peer'))", 'message': 'ERP threw error creating new Demo', 'user_details': 'ERP threw error creating new Demo'} 

Also I looked into the log of the pipeline deployment, and noticed the following. looks like the openwhisk portion was not setup correctly.

<img width="799" alt="screen shot 2017-08-05 at 9 49 48 am" src="https://user-images.githubusercontent.com/17069714/28996321-a26ece04-79c3-11e7-9ce5-d4a7ac3f84cf.png">

**Comment by l2fprod** [comment]
indeed. Do you have a space character in your org or space?

**Comment by cenyuzhang** [comment]
I don't have any space character in my org or space.

Is there any easy way to un-deploy everything, including the pods, services on kubernetes? I will try to deploy it again, and see if it will work

**Comment by l2fprod** [comment]
The Controller and ERP pipelines have an UNDEPLOY stage that you can run manually:

![image](https://user-images.githubusercontent.com/12746550/29058934-6869911a-7c13-11e7-9c6a-e72f5251b1de.png)

It will remove the deployments, pods, services, then you can run the pipelines again.

**Comment by cenyuzhang** [comment]
@l2fprod is there any way not to use the bluemix registry for container images? My account doesn't allow to push more container images due to size limit. Is it possible to build the images locally and then push to Kubernetes cluster? Thanks.

**Comment by l2fprod** [comment]
you could run everything locally with minikube or push the images to Docker Hub and change the deployment shell scripts/yaml.

**Comment by cenyuzhang** [comment]
@l2fprod thanks for all the help. It's working for me now. I will close the issue
